Adds GlobalModels global, minor refactors
obhq/obliteration pull request #1118
Opened 2024-11-19 20:18 UTC by SuchAFuriousDeath

2024-11-19 20:38 UTC, ultimaweapon commented
> I guess VmmEventHandle will have to wrap an impl FnMut(VmmEvent) + Clone closure?

Should be `Arc<dyn Fn(...)>` instead.

2024-11-19 20:41 UTC, SuchAFuriousDeath commented
> > I guess VmmEventHandle will have to wrap an impl FnMut(VmmEvent) + Clone closure?
> 
> Should be `Arc<dyn Fn(...)>` instead.

Close enough :sweat_smile:

2024-11-19 20:46 UTC, ultimaweapon commented
I don't think global models are a good idea. Why do we need it? It should be passing to the main window and downstream to all of its children instead.

2024-11-19 20:50 UTC, SuchAFuriousDeath commented
> > I don't think global models are a good idea. Why do we need it? It should be passing to the main window and downstream to all of its children instead.
> 
> When launching in debug, there is no main window (and the screen isn't its child anyway). Maybe that's the fix that needs fixing here 🤔

But that's actually not the real problem. The real problem is that I don't like having to pass the devices and profiles through several elements down to where we actually need them. If they're global, we can just directly access them right where we need them (in the ComboBoxes)

2024-11-19 20:53 UTC, ultimaweapon commented
> > > I don't think global models are a good idea. Why do we need it? It should be passing to the main window and downstream to all of its children instead.
> > 
> > 
> > When launching in debug, there is no main window (and the screen isn't its child anyway). Maybe that's the fix that needs fixing here 🤔
> 
> But that's actually not the real problem. The real 'problem' is that I don't like having to pass the devices and profiles through several elements down to where we actually need them. If they're global, we can just directly access them right where we need them (in the ComboBoxes)

What you don't like here are actually a good practice.

2024-11-19 20:59 UTC, SuchAFuriousDeath commented
> > > > I don't think global models are a good idea. Why do we need it? It should be passing to the main window and downstream to all of its children instead.
> > > 
> > > 
> > > When launching in debug, there is no main window (and the screen isn't its child anyway). Maybe that's the fix that needs fixing here 🤔
> > 
> > 
> > But that's actually not the real problem. The real 'problem' is that I don't like having to pass the devices and profiles through several elements down to where we actually need them. If they're global, we can just directly access them right where we need them (in the ComboBoxes)
> 
> What you don't like here are actually a good practice.

Oops :D

2024-11-20 16:01 UTC, ultimaweapon requested changes

2024-11-20 16:01 UTC, ultimaweapon commented on gui/src/main.rs
> +    let profiles = vec![Profile::default()];
Better to centralize this now so we don't have a duplicated code.

2024-11-20 16:20 UTC, ultimaweapon approved these changes

2024-11-20 16:20 UTC, merged