Change to Visual Studio 2022
obhq/obliteration pull request #164
Opened 2023-02-27 20:09 UTC by VocalFan

This upgrades the Windows 2019 runners to Windows 2022 runners! Along with this, we will now use Visual Studio 2022.

2023-02-28 01:25 UTC, flyingtincan commented on README.md
>    - Your system must not have 2022 installed
This line is now inaccurate

2023-02-28 01:27 UTC, VocalFan commented on README.md
>    - Your system must not have 2022 installed
Wowwwww, I really missed that XD

2023-03-01 07:11 UTC, ultimaweapon requested changes

2023-03-01 07:11 UTC, ultimaweapon commented on README.md
> +- [Microsoft Visual C++ 2022 Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist). It's likely your system already has it, so try to run Obliteration first.
Better to leave the error message so the users can distinguish from other errors.

2023-03-01 08:56 UTC, ultimaweapon approved these changes

2023-03-01 08:56 UTC, merged