General additions + Implementations
obhq/obliteration pull request #433
Opened 2023-11-12 06:15 UTC by VocalFan

Added Syscall 69 and 70, along with adding regkeys from 0x01010000 to 0x01400000, and adding the missing Display for `DEVENV_TOOL_USE_DEFAULT_LIB`, ending off with a use of `clippy --fix` to clean up any odd code.

Also here's your proof ultima:

![image](https://github.com/obhq/obliteration/assets/45863583/316adb1c-fdc9-45b0-8230-1d3f7c4ec6df)

2023-11-12 06:56 UTC, ultimaweapon requested changes

2023-11-12 06:56 UTC, ultimaweapon commented on src/kernel/src/main.rs
> +    #[default]
`Native` cannot be used on non-x86.

2023-11-12 06:56 UTC, ultimaweapon commented on src/kernel/src/ee/llvm/mod.rs
> +    fn set_syscalls(&self, _v: Syscalls) {
Rename things here is not a good idea since @bayedieng might be working here.

2023-11-12 06:57 UTC, VocalFan commented
Bruh, Ultima, I can't believe you're already awake lel

2023-11-12 06:58 UTC, VocalFan commented
But alright, guess clippy had some dumb moments.

2023-11-12 10:07 UTC, ultimaweapon requested changes

2023-11-12 10:07 UTC, ultimaweapon commented on src/kernel/src/regmgr/key.rs
> +    // pub const REGISTRY_VERSION: Self = Self(0);
Why keeping this?

2023-11-12 13:58 UTC, VocalFan commented on src/kernel/src/regmgr/key.rs
> +    // pub const REGISTRY_VERSION: Self = Self(0);
Ah crap, forgot to remove it x3 sorryyy

2023-11-12 15:15 UTC, VocalFan commented
@ultimaweapon Ready for another check :3

2023-11-13 02:09 UTC, ultimaweapon approved these changes

2023-11-13 02:09 UTC, merged