Implement kern.proc.sanitizer
obhq/obliteration pull request #449
Opened 2023-11-17 14:04 UTC by SuchAFuriousDeath

Closes #416.

2023-11-17 15:52 UTC, ultimaweapon requested changes

2023-11-17 16:35 UTC, SuchAFuriousDeath commented on src/kernel/src/sysctl/mod.rs
> +    name: "sanitizer",
Not intentional.

2023-11-17 20:51 UTC, SuchAFuriousDeath commented
I suspect the mysterious function is some sort of a is_debug check or something like that.

2023-11-18 02:28 UTC, ultimaweapon approved these changes

2023-11-18 02:28 UTC, merged