Implement cn_nameiop equivalent
obhq/obliteration pull request #573
Opened 2024-01-26 21:44 UTC by SuchAFuriousDeath

2024-01-26 21:46 UTC, SuchAFuriousDeath commented
@ultimaweapon This is roughly what I had in mind.

2024-01-27 06:05 UTC, ultimaweapon requested changes

2024-01-27 06:05 UTC, ultimaweapon commented on src/kernel/src/fs/path.rs
> +pub enum ComponentName<'a> {
`VPathComponent` should be a better name.

2024-01-27 06:05 UTC, ultimaweapon commented on src/kernel/src/fs/mod.rs
> +    fn namei(
I'm not really a fan of `namei` because it make no sense.

2024-01-27 06:05 UTC, ultimaweapon commented on src/kernel/src/fs/mod.rs
> +
We probably don't need this due to my previous comment.

2024-01-27 10:59 UTC, ultimaweapon requested changes

2024-01-27 10:59 UTC, ultimaweapon commented on src/kernel/src/fs/path.rs
> +pub enum LookupOp {
This one should not be here.

2024-01-27 10:59 UTC, ultimaweapon commented on src/kernel/src/fs/path.rs
> +    Normal { name: &'a str },
I think `Name(&'a str)` looks better. It is also much easier to work with unnamed field than named field.

2024-01-28 06:00 UTC, ultimaweapon commented on src/kernel/src/fs/path.rs
> +pub enum LookupOp {
Seems like to missed this one. It should be in the root of `fs` instead of `path`.

2024-02-24 08:36 UTC, closed without merging