vm.budgets.mlock_avail name2oid
obhq/obliteration pull request #656
Opened 2024-02-17 00:13 UTC by mikusp

2024-02-17 00:14 UTC, SuchAFuriousDeath commented
You forgot to draw it into the tree :(

2024-02-17 00:23 UTC, mikusp commented
On the second look I'm not sure if I've read the tree correctly 🤔 It looks in ghidra like 314 is a child of 313 but judging from other sysctls that feels wrong 😓

2024-02-17 00:26 UTC, SuchAFuriousDeath requested changes

2024-02-17 00:26 UTC, SuchAFuriousDeath commented on src/kernel/src/sysctl/mod.rs
> +    kind: Sysctl::CTLFLAG_RD | Sysctl::CTLFLAG_WR | Sysctl::CTLTYPE_NODE,
Use Sysctl::CTLFLAG_RW instead of the first two

2024-02-17 00:26 UTC, SuchAFuriousDeath commented on src/kernel/src/sysctl/mod.rs
> +    first: Some(&VM_BUDGETS_MLOCK_AVAIL), // TODO: use a proper value
Isn't it already the proper value? :thinking:

2024-02-18 15:31 UTC, SuchAFuriousDeath approved these changes

2024-02-18 15:49 UTC, merged