refactors idt
obhq/obliteration pull request #661
Opened 2024-02-17 03:09 UTC by SuchAFuriousDeath

2024-02-17 19:30 UTC, SuchAFuriousDeath commented
I think VnodeBackend::open should return a VFileType

2024-02-18 14:40 UTC, ultimaweapon requested changes

2024-02-18 14:40 UTC, ultimaweapon commented on src/kernel/src/namedobj/mod.rs
> +    pub fn new(name: impl ToString, data: usize) -> Self {
Better to use `Into<String>` instead so it does not allocate a new string if `name` is a `String`.

2024-02-18 14:51 UTC, mikusp submitted a review, later dismissed

2024-02-18 20:27 UTC, mikusp approved these changes

2024-02-18 20:28 UTC, merged

2024-02-18 22:57 UTC, SuchAFuriousDeath commented
> I think VnodeBackend::open should return a VFileType btw

@ultimaweapon Because of this: 
<img width="604" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/0feb8540-4523-4d27-9694-0f54ae5e0b54">
Also, I'm dumb and realized just now that f_vnode is set here in kern_open:
<img width="649" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/b58b451c-9e07-4f4f-b1b9-243789124acc">