Initialize RngManager
obhq/obliteration pull request #670
Opened 2024-02-18 17:45 UTC by mikusp

2024-02-24 06:08 UTC, ultimaweapon requested changes

2024-02-24 06:08 UTC, ultimaweapon commented on src/kernel/src/rng/mod.rs
> +            MakeDev::MAKEDEV_ETERNAL,
What I saw on the PS4 is 0 for this one.

2024-02-24 06:08 UTC, ultimaweapon commented on src/kernel/src/rng/mod.rs
> +        _td: Option<&VThread>,
Better to use `_` for all parameters here.

2024-03-24 09:54 UTC, SuchAFuriousDeath commented
Superseded by #729

2024-03-24 09:54 UTC, closed without merging