Additions to the recompiler.
obhq/obliteration pull request #88
Opened 2023-01-25 19:53 UTC by Mou-Ikkai

Added all the Registers I could find.
Also added the codes: Movzx_r32_rm8, Nopd, Setne_rm8, Sub_64_imm8

2023-01-25 20:06 UTC, Mou-Ikkai commented
I'd also like to say I tested all these operations, and none of them threw an error or gave an unexpected behavior.

2023-01-26 04:00 UTC, ultimaweapon requested changes
You did a good job :) Just some issues.

2023-01-26 04:00 UTC, ultimaweapon commented on src/kernel/src/process/module/recompiler.rs
> +                Code::Movzx_r32_rm8 => (self.preserve(i), false),
We can't preserve this one because the source operand may use RIP-relative, which we do not supported yet.

2023-01-26 04:00 UTC, ultimaweapon commented on src/kernel/src/process/module/recompiler.rs
> +                Code::Setne_rm8 => (self.preserve(i), false),
Same here.

2023-01-26 04:00 UTC, ultimaweapon commented on src/kernel/src/process/module/recompiler.rs
> +            Register::RBP => Register::RSP,
We cannot use `RSP` as a general purpose register because it must be pointing to the stack all the time.

2023-01-26 04:00 UTC, ultimaweapon commented on src/kernel/src/process/module/recompiler.rs
> +            Register::RSP => Register::RBP,
`keep` argument should never be `RSP` because we should not have any cases to transform any instructions that writing to it.

2023-01-26 05:19 UTC, Mou-Ikkai commented
I fixed these issues, however, I'm working on a part 2 for this, so hold until next commit.

2023-01-26 05:53 UTC, Mou-Ikkai commented
@ultimaweapon Have fun! I would keep going but... I'm stuck on Imul_r32_rm32_imm8

2023-01-26 10:45 UTC, ultimaweapon requested changes
Impressive! Just some small mistakes.

2023-01-26 10:45 UTC, ultimaweapon commented on src/kernel/src/process/module/recompiler.rs
> +                Code::And_EAX_imm32 => (self.transform_and_eax_imm32(i), false),
This one can be preserved because it does not access the memory.

2023-01-26 10:45 UTC, ultimaweapon commented on src/kernel/src/process/module/recompiler.rs
> +        if i.op0_kind() == OpKind::Memory && i.is_ip_rel_memory_operand() {
We need to check the second operand, not first.

2023-01-26 12:25 UTC, ultimaweapon approved these changes

2023-01-26 12:25 UTC, merged