Implements run and states for MacOS
obhq/obliteration pull request #909
Opened 2024-07-28 19:37 UTC by SuchAFuriousDeath

2024-07-28 21:55 UTC, SuchAFuriousDeath commented
Not sure what's up with the Windows build

2024-07-28 23:03 UTC, SuchAFuriousDeath commented
It seems that we can't access the EFER register, but I assume the features we are interested in are already turned on?.

2024-07-28 23:42 UTC, SuchAFuriousDeath commented
Not sure what to do about set_cs :(

2024-07-29 00:29 UTC, SuchAFuriousDeath commented
I assume we're interested in ARM Linux and ARM Windows as well?

2024-07-29 04:40 UTC, ultimaweapon commented
Seems like the Hypervisor Framework on macOS is the worst. A lot of restrictions.

> I assume we're interested in ARM Linux and ARM Windows as well?

If someone wiling to work on this.

2024-07-29 04:44 UTC, ultimaweapon commented
BTW I'm surprised that WHP has a very good API.

2024-07-29 04:54 UTC, VocalFan commented
> BTW I'm surprised that WHP has a very good API.

Microsoft takes pride in Hyper-V, so... Makes sense.

2024-07-29 12:37 UTC, SuchAFuriousDeath commented
I think the segment registers can be set and read with this:
https://developer.apple.com/documentation/hypervisor/1441144-hv_vmx_vcpu_write_vmcs?language=objc

Here is a list of field ids. The segment registers do appear more than once. For example, for cs there's, VMCS_GUEST_CS, VMCS_HOST_CS, VMCS_GUEST_CS_LIMIT and VMCS_GUEST_CS_AR

https://developer.apple.com/documentation/hypervisor/1469436-virtual_machine_control_structur?language=objc

2024-07-29 12:51 UTC, ultimaweapon commented
Should be `VMCS_GUEST_CS`. Not sure what the purpose of the other ones.

2024-07-29 13:43 UTC, SuchAFuriousDeath commented
I guess the contents are the same as .Segment.Anonymous.Attributes on Windows? :eyes:

2024-07-29 14:59 UTC, ultimaweapon commented
> I guess the contents are the same as .Segment.Anonymous.Attributes on Windows? 👀

This really implementation specific. Maybe finding some example on the internet should be easier if the docs does not help?

2024-07-29 15:09 UTC, ultimaweapon commented
Just found a very good example: https://github.com/utshina/AHF-simple

2024-07-29 21:04 UTC, SuchAFuriousDeath commented
A good example indeed. I managed to implemente exit_reason for x86 mac because of it

2024-07-31 18:08 UTC, SuchAFuriousDeath commented
By the way the vm stuff seems to work correctly for now on my Linux machine.

2024-08-01 08:32 UTC, ultimaweapon commented
No.

2024-08-01 09:14 UTC, SuchAFuriousDeath commented
Oh, Where does it stop for you?

2024-08-01 10:24 UTC, ultimaweapon commented
It is never stop because of `hlt`. In other words, it work as expected. Did you try on the latest `main` of from your branch?

2024-08-01 11:08 UTC, SuchAFuriousDeath commented
Both, In main, I panic here 
https://github.com/obhq/obliteration/blob/573eca32403983bd2b4c6cafda9ed9630a3362b5/src/core/src/vmm/mod.rs#L615-L617
In my branch, i the same things happens in a different place, but it is equivalent.

2024-08-01 11:15 UTC, ultimaweapon commented
The problem may be caused by a different Linux version or different CPU. What is your Linux version and CPU model? I was tested this with Arch on Ryzen 5600G.

2024-08-01 11:28 UTC, SuchAFuriousDeath commented
EndeavourOS (Which is Arch-based), kernel version 6.9.7, cpu 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz

2024-08-01 11:30 UTC, ultimaweapon commented
I suspect this #905 or https://github.com/firecracker-microvm/firecracker/issues/668 if your Linux running inside a VM.

2024-08-01 11:35 UTC, SuchAFuriousDeath commented
I completely forgot that the issue applies to me :joy:  That might very well be it.

2024-08-01 11:36 UTC, SuchAFuriousDeath commented
No nested VMs for me though.

2024-08-02 12:16 UTC, SuchAFuriousDeath commented
> 

It doesn't seem to be it

2024-08-02 12:37 UTC, ultimaweapon commented
Strange. At least on Windows with Ryzen it is working according to https://github.com/obhq/obliteration/pull/916#issue-2443300798

2024-08-02 12:40 UTC, ultimaweapon commented
Can we ask another people who are using Linux with AMD to test this? If it is working I'm pretty sure it is because of #905.

2024-08-02 12:46 UTC, SuchAFuriousDeath commented
What address should I set fr the TSS?

2024-08-02 12:51 UTC, ultimaweapon commented
I don't know but any virtual address need to be mapped to physical address via page table otherwise the CPU will trigger page fault, which we currently does not setup a handler to handle it.

2024-08-02 12:55 UTC, SuchAFuriousDeath commented
But the TSS that we have to set is a physical address, no?

2024-08-02 12:57 UTC, ultimaweapon commented
I don't know. You should take a look on Intel manual. But AFAIK the only place that need to be a physical address is page tables and `cr3`.

2024-08-02 13:09 UTC, SuchAFuriousDeath commented
![image](https://github.com/user-attachments/assets/38726660-cbb7-439d-9b1c-679c592aabfd)
It seems that I can get some information about the exit

2024-08-02 14:21 UTC, ultimaweapon commented
BTW you should not make this PR contain too many things.

2024-08-02 14:38 UTC, SuchAFuriousDeath commented
The exception is 0x80000021, the error code is 0.

2024-08-02 16:12 UTC, ultimaweapon commented
We are not alone: https://forum.proxmox.com/threads/vm-shutdown-kvm-entry-failed-hardware-error-0x80000021.109410/

2024-08-02 16:37 UTC, ultimaweapon commented
In our case I suspect TSS because `0x80000021` mean invalid guest state.

2024-08-03 18:42 UTC, ultimaweapon requested changes

2024-08-03 18:42 UTC, ultimaweapon commented on src/core/src/vmm/cpu.rs
> +    Other,
We we need this?

2024-08-03 18:42 UTC, ultimaweapon commented on src/core/src/vmm/mod.rs
> +            reason => todo!("unhandled VM exit reason: {reason:?}"),
This should not needed here. It should already handled by CPU implementation.

2024-08-03 18:45 UTC, SuchAFuriousDeath commented on src/core/src/vmm/cpu.rs
> +    Other,
I'll revert it

2024-08-04 00:00 UTC, ultimaweapon approved these changes

2024-08-04 00:01 UTC, merged