Added implementations to recompiler.rs
obhq/obliteration pull request #92
Opened 2023-01-27 06:15 UTC by Mou-Ikkai

2023-01-28 11:33 UTC, ultimaweapon requested changes

2023-01-28 11:33 UTC, ultimaweapon commented on src/kernel/src/process/module/recompiler.rs
> +                Code::Add_rm8_r8 => (self.transform_add_rm8_r8(i), true),
This one cannot mark and ended. The only kind that can mark as ended is unconditional control transfer without return back.

2023-01-28 11:33 UTC, ultimaweapon commented on src/kernel/src/process/module/recompiler.rs
> +                Code::Mov_r8_imm8 => (self.transform_mov_r8_imm8(i), true),
Same here.

2023-01-28 11:33 UTC, ultimaweapon commented on src/kernel/src/process/module/recompiler.rs
> +                Code::Jo_rel8_64 | Code::Jo_rel32_64 => (self.transform_jo_rel(i), true),
Same here.

2023-01-29 17:49 UTC, Mou-Ikkai commented
Final changes I could implement before reaching INVALID error as discussed in our Matrix chat.
`Code: INVALID | Regs: {None, None, None, None} | OP_Kinds: {Register, Register, Register, Register}`
After merge:
@ultimaweapon `I'll try to implement this so your PR should handle that call as the last instruction.`

2023-01-30 17:03 UTC, ultimaweapon requested changes

2023-01-30 17:03 UTC, ultimaweapon commented on src/kernel/src/process/module/recompiler.rs
> +            panic!("XCHG r8, r/m8 with second operand as RIP-relative is not supported yet.");
We don't need this.

2023-01-30 17:03 UTC, ultimaweapon commented on src/kernel/src/process/module/recompiler.rs
> +                Code::Xor_EAX_imm32 => (self.transform_xor_eax_imm32(i), false),
These one can be preserved.

2023-01-30 17:03 UTC, ultimaweapon commented on src/kernel/src/process/module/recompiler.rs
> +    // Get register other than `keep`.
`//` and `///` have a different meaning in Rust.

2023-01-30 20:54 UTC, Mou-Ikkai commented
@ultimaweapon Please for the love of god specify on the imui suggestions because I implemented them to the docs I saw-

2023-01-31 03:27 UTC, Mou-Ikkai commented
I hope that change to imul_2 was it, seeing as imul_3 doesn't work due to the other registers being u32, not u8

2023-01-31 13:03 UTC, ultimaweapon requested changes

2023-01-31 13:03 UTC, ultimaweapon commented on src/kernel/src/process/module/recompiler.rs
> +                Code::Mov_rm8_imm8 => (self.preserve(i), false),
This one cannot be preserved.

2023-01-31 16:19 UTC, ultimaweapon submitted a review, later dismissed

2023-01-31 17:41 UTC, ultimaweapon approved these changes

2023-01-31 17:41 UTC, merged